import {
  AlertResponse,
  CaseDetail,
  CashoutLocation,
  CashoutPredictionResponse,
  Complaint,
  DashboardStats,
  EntityNetworkGraph,
} from "./types";

// ==========================================
// 1. NCRP CITIZEN COMPLAINTS (~42 SEEDED)
// ==========================================
export const SEEDED_COMPLAINTS: Complaint[] = [
  {
    id: "NCRP-2026-8812",
    case_id: "CASE-2026-4401",
    victim_name: "PRAISY I",
    victim_phone: "+91 98112 44321",
    victim_upi: "praisy.i@okhdfcbank",
    victim_account: "HDFC-4902198012",
    victim_bank: "HDFC Bank",
    fraud_category: "Electricity Bill Threat Phishing",
    reported_amount: 45000,
    incident_time: "2026-09-28T09:14:00Z",
    reported_time: "2026-09-28T09:42:00Z",
    status: "INVESTIGATING",
    city: "New Delhi",
  },
  {
    id: "NCRP-2026-8815",
    case_id: "CASE-2026-4401",
    victim_name: "ARYAN MANOJ",
    victim_phone: "+91 97180 99412",
    victim_upi: "aryan.manoj@icici",
    victim_account: "ICICI-0029104812",
    victim_bank: "ICICI Bank",
    fraud_category: "Electricity Bill Threat Phishing",
    reported_amount: 82000,
    incident_time: "2026-09-28T09:30:00Z",
    reported_time: "2026-09-28T10:05:00Z",
    status: "INVESTIGATING",
    city: "Noida",
  },
  {
    id: "NCRP-2026-8819",
    case_id: "CASE-2026-4401",
    victim_name: "ABHINAV",
    victim_phone: "+91 94220 18471",
    victim_upi: "abhinav@sbi",
    victim_account: "SBI-3091823901",
    victim_bank: "State Bank of India",
    fraud_category: "Electricity Bill Threat Phishing",
    reported_amount: 120000,
    incident_time: "2026-09-28T09:45:00Z",
    reported_time: "2026-09-28T10:20:00Z",
    status: "INVESTIGATING",
    city: "Ghaziabad",
  },
  {
    id: "NCRP-2026-8824",
    case_id: "CASE-2026-4401",
    victim_name: "ANIRUDH",
    victim_phone: "+91 98301 22910",
    victim_upi: "anirudh@okaxis",
    victim_account: "AXIS-9182039102",
    victim_bank: "Axis Bank",
    fraud_category: "Electricity Bill Threat Phishing",
    reported_amount: 60000,
    incident_time: "2026-09-28T10:10:00Z",
    reported_time: "2026-09-28T10:35:00Z",
    status: "INVESTIGATING",
    city: "Gurugram",
  },
  {
    id: "NCRP-2026-8830",
    case_id: "CASE-2026-4401",
    victim_name: "ARYAANSH",
    victim_phone: "+91 98200 48192",
    victim_upi: "aryaansh@kotak",
    victim_account: "KOTAK-581902819",
    victim_bank: "Kotak Mahindra",
    fraud_category: "Electricity Bill Threat Phishing",
    reported_amount: 95000,
    incident_time: "2026-09-28T10:22:00Z",
    reported_time: "2026-09-28T10:50:00Z",
    status: "INVESTIGATING",
    city: "Faridabad",
  },
  {
    id: "NCRP-2026-8835",
    case_id: "CASE-2026-4401",
    victim_name: "Vikas Aggarwal",
    victim_phone: "+91 99100 37194",
    victim_upi: "vikas.aggarwal@pnb",
    victim_account: "PNB-0192830192",
    victim_bank: "Punjab National Bank",
    fraud_category: "Electricity Bill Threat Phishing",
    reported_amount: 145000,
    incident_time: "2026-09-28T10:40:00Z",
    reported_time: "2026-09-28T11:15:00Z",
    status: "INVESTIGATING",
    city: "Delhi",
  },

  // Case 4402 - Telegram Part-Time Job Scam
  {
    id: "NCRP-2026-8841",
    case_id: "CASE-2026-4402",
    victim_name: "Siddharth Roy",
    victim_phone: "+91 98711 02931",
    victim_upi: "siddharth.roy@paytm",
    victim_account: "PYTM-9102839102",
    victim_bank: "Paytm Payments Bank",
    fraud_category: "Telegram Part-Time Task Scam",
    reported_amount: 180000,
    incident_time: "2026-09-28T08:15:00Z",
    reported_time: "2026-09-28T09:00:00Z",
    status: "INVESTIGATING",
    city: "Noida",
  },
  {
    id: "NCRP-2026-8844",
    case_id: "CASE-2026-4402",
    victim_name: "Pooja Hegde",
    victim_phone: "+91 99201 88471",
    victim_upi: "pooja.h@hdfcbank",
    victim_account: "HDFC-5829103910",
    victim_bank: "HDFC Bank",
    fraud_category: "Telegram Part-Time Task Scam",
    reported_amount: 320000,
    incident_time: "2026-09-28T08:45:00Z",
    reported_time: "2026-09-28T09:30:00Z",
    status: "INVESTIGATING",
    city: "New Delhi",
  },
  {
    id: "NCRP-2026-8848",
    case_id: "CASE-2026-4402",
    victim_name: "Gaurav Malhotra",
    victim_phone: "+91 98103 44910",
    victim_upi: "gaurav.mal@icici",
    victim_account: "ICICI-0019283019",
    victim_bank: "ICICI Bank",
    fraud_category: "Telegram Part-Time Task Scam",
    reported_amount: 240000,
    incident_time: "2026-09-28T09:10:00Z",
    reported_time: "2026-09-28T09:50:00Z",
    status: "INVESTIGATING",
    city: "Gurugram",
  },
  {
    id: "NCRP-2026-8852",
    case_id: "CASE-2026-4402",
    victim_name: "Ritu Singhal",
    victim_phone: "+91 97110 59281",
    victim_upi: "ritu.singhal@axis",
    victim_account: "AXIS-1029384910",
    victim_bank: "Axis Bank",
    fraud_category: "Telegram Part-Time Task Scam",
    reported_amount: 150000,
    incident_time: "2026-09-28T09:40:00Z",
    reported_time: "2026-09-28T10:15:00Z",
    status: "INVESTIGATING",
    city: "Delhi",
  },

  // Case 4403 - Aadhaar Biometric / Digital Arrest Extortion
  {
    id: "NCRP-2026-8860",
    case_id: "CASE-2026-4403",
    victim_name: "Dr. Alok Nath",
    victim_phone: "+91 98100 11928",
    victim_upi: "alok.nath@sbi",
    victim_account: "SBI-1928301928",
    victim_bank: "State Bank of India",
    fraud_category: "CBI Impersonation & Digital Arrest",
    reported_amount: 850000,
    incident_time: "2026-09-28T07:30:00Z",
    reported_time: "2026-09-28T09:15:00Z",
    status: "CRITICAL",
    city: "New Delhi",
  },
  {
    id: "NCRP-2026-8864",
    case_id: "CASE-2026-4403",
    victim_name: "Shalini Kapoor",
    victim_phone: "+91 98182 30192",
    victim_upi: "shalini.k@hdfc",
    victim_account: "HDFC-8192039102",
    victim_bank: "HDFC Bank",
    fraud_category: "CBI Impersonation & Digital Arrest",
    reported_amount: 620000,
    incident_time: "2026-09-28T08:00:00Z",
    reported_time: "2026-09-28T09:40:00Z",
    status: "CRITICAL",
    city: "Noida",
  },

  // Case 4404 - Instant Loan App Blackmail
  {
    id: "NCRP-2026-8871",
    case_id: "CASE-2026-4404",
    victim_name: "Amitabh Sen",
    victim_phone: "+91 99203 19283",
    victim_upi: "amitabh.sen@ybl",
    victim_account: "YES-0192830192",
    victim_bank: "Yes Bank",
    fraud_category: "Predatory Loan App Harassment",
    reported_amount: 110000,
    incident_time: "2026-09-28T06:10:00Z",
    reported_time: "2026-09-28T07:45:00Z",
    status: "INVESTIGATING",
    city: "Faridabad",
  },
  {
    id: "NCRP-2026-8875",
    case_id: "CASE-2026-4404",
    victim_name: "Neha Joshi",
    victim_phone: "+91 97172 83910",
    victim_upi: "neha.joshi@icici",
    victim_account: "ICICI-9201928301",
    victim_bank: "ICICI Bank",
    fraud_category: "Predatory Loan App Harassment",
    reported_amount: 95000,
    incident_time: "2026-09-28T07:00:00Z",
    reported_time: "2026-09-28T08:20:00Z",
    status: "INVESTIGATING",
    city: "Ghaziabad",
  },

  // Case 4405 - Fake Stock Trading Portfolio
  {
    id: "NCRP-2026-8880",
    case_id: "CASE-2026-4405",
    victim_name: "Karan Bajaj",
    victim_phone: "+91 98110 92019",
    victim_upi: "karan.bajaj@kotak",
    victim_account: "KOTAK-9102938192",
    victim_bank: "Kotak Mahindra",
    fraud_category: "Institutional IPO Trading Scam",
    reported_amount: 1400000,
    incident_time: "2026-09-27T16:00:00Z",
    reported_time: "2026-09-28T08:30:00Z",
    status: "CRITICAL",
    city: "Gurugram",
  },
  {
    id: "NCRP-2026-8884",
    case_id: "CASE-2026-4405",
    victim_name: "Deepak Chawla",
    victim_phone: "+91 98188 39102",
    victim_upi: "deepak.c@axis",
    victim_account: "AXIS-2019283019",
    victim_bank: "Axis Bank",
    fraud_category: "Institutional IPO Trading Scam",
    reported_amount: 1150000,
    incident_time: "2026-09-27T17:15:00Z",
    reported_time: "2026-09-28T09:00:00Z",
    status: "CRITICAL",
    city: "New Delhi",
  },

  // Additional realistic NCRP Complaints (Total ~42)
  ...[
    { id: "NCRP-2026-8890", case_id: "CASE-2026-4406", victim_name: "Tanvi Saxena", amount: 65000, cat: "SIM Swap / Banking OTP Theft", city: "Delhi" },
    { id: "NCRP-2026-8891", case_id: "CASE-2026-4406", victim_name: "Mohit Bansal", amount: 78000, cat: "SIM Swap / Banking OTP Theft", city: "Noida" },
    { id: "NCRP-2026-8892", case_id: "CASE-2026-4406", victim_name: "Sanjay Gupta", amount: 92000, cat: "SIM Swap / Banking OTP Theft", city: "Gurugram" },
    { id: "NCRP-2026-8895", case_id: "CASE-2026-4407", victim_name: "Ritika Oberoi", amount: 48000, cat: "E-Commerce QR Code Refund Fraud", city: "New Delhi" },
    { id: "NCRP-2026-8896", case_id: "CASE-2026-4407", victim_name: "Naveen Juneja", amount: 53000, cat: "E-Commerce QR Code Refund Fraud", city: "Faridabad" },
    { id: "NCRP-2026-8897", case_id: "CASE-2026-4407", victim_name: "Suresh Menon", amount: 67000, cat: "E-Commerce QR Code Refund Fraud", city: "Ghaziabad" },
    { id: "NCRP-2026-8901", case_id: "CASE-2026-4408", victim_name: "Kavita Rao", amount: 210000, cat: "Matrimonial Honeytrap Extortion", city: "Noida" },
    { id: "NCRP-2026-8902", case_id: "CASE-2026-4408", victim_name: "Harish Pathak", amount: 185000, cat: "Matrimonial Honeytrap Extortion", city: "Delhi" },
    { id: "NCRP-2026-8905", case_id: "CASE-2026-4409", victim_name: "Anand Murthy", amount: 350000, cat: "Customs Parcel Drug Threat Scam", city: "Gurugram" },
    { id: "NCRP-2026-8906", case_id: "CASE-2026-4409", victim_name: "Usha Raman", amount: 420000, cat: "Customs Parcel Drug Threat Scam", city: "New Delhi" },
    { id: "NCRP-2026-8910", case_id: "CASE-2026-4410", victim_name: "Rohan Khanna", amount: 95000, cat: "Credit Card Limit Increase Phishing", city: "Noida" },
    { id: "NCRP-2026-8911", case_id: "CASE-2026-4410", victim_name: "Bhavna Mittal", amount: 110000, cat: "Credit Card Limit Increase Phishing", city: "Delhi" },
    { id: "NCRP-2026-8915", case_id: "CASE-2026-4411", victim_name: "Sameer Sheikh", amount: 175000, cat: "Work-From-Home Rating Syndicate", city: "Faridabad" },
    { id: "NCRP-2026-8916", case_id: "CASE-2026-4411", victim_name: "Divya Nambiar", amount: 190000, cat: "Work-From-Home Rating Syndicate", city: "Gurugram" },
    { id: "NCRP-2026-8920", case_id: "CASE-2026-4412", victim_name: "Akash Singhal", amount: 80000, cat: "Fake Lottery / KBC WhatsApp Scheme", city: "Ghaziabad" },
    { id: "NCRP-2026-8921", case_id: "CASE-2026-4412", victim_name: "Prerna Vohra", amount: 125000, cat: "Fake Lottery / KBC WhatsApp Scheme", city: "Delhi" },
    { id: "NCRP-2026-8922", case_id: "CASE-2026-4412", victim_name: "Manish Poddar", amount: 95000, cat: "Fake Lottery / KBC WhatsApp Scheme", city: "New Delhi" },
    { id: "NCRP-2026-8925", case_id: "CASE-2026-4401", victim_name: "Kailash Chand", amount: 45000, cat: "Electricity Bill Threat Phishing", city: "Delhi" },
    { id: "NCRP-2026-8926", case_id: "CASE-2026-4402", victim_name: "Swati Narang", amount: 135000, cat: "Telegram Part-Time Task Scam", city: "Noida" },
    { id: "NCRP-2026-8927", case_id: "CASE-2026-4403", victim_name: "Girish Tiwari", amount: 500000, cat: "CBI Impersonation & Digital Arrest", city: "Gurugram" },
    { id: "NCRP-2026-8928", case_id: "CASE-2026-4404", victim_name: "Lalit Kaushik", amount: 88000, cat: "Predatory Loan App Harassment", city: "Delhi" },
    { id: "NCRP-2026-8929", case_id: "CASE-2026-4405", victim_name: "Pooja Batra", amount: 980000, cat: "Institutional IPO Trading Scam", city: "New Delhi" },
  ].map((item, idx) => ({
    id: item.id,
    case_id: item.case_id,
    victim_name: item.victim_name,
    victim_phone: `+91 98${(100 + idx).toString().padStart(3, "0")} ${10000 + idx * 7}`,
    victim_upi: `${item.victim_name.toLowerCase().replace(/\s+/g, ".")}@bank`,
    victim_account: `BANK-009281${idx}`,
    victim_bank: "Scheduled Commercial Bank",
    fraud_category: item.cat,
    reported_amount: item.amount,
    incident_time: "2026-09-28T07:00:00Z",
    reported_time: "2026-09-28T08:15:00Z",
    status: "INVESTIGATING",
    city: item.city,
  })),
];

// ==========================================
// 2. DELHI-NCR ATM / CSP HOTSPOTS (26 NODES)
// ==========================================
export const SEEDED_HOTSPOTS: CashoutLocation[] = [
  {
    id: "LOC-DEL-01",
    name: "State Bank of India — Connaught Place Inner Circle ATM",
    type: "ATM",
    bank: "State Bank of India",
    address: "Block B, Radial 3, Connaught Place, New Delhi",
    city: "New Delhi",
    latitude: 28.6328,
    longitude: 77.2197,
    cctv_available: true,
    historical_fraud_count: 19,
  },
  {
    id: "LOC-DEL-02",
    name: "HDFC Bank — Karol Bagh Gurudwara Road ATM",
    type: "ATM",
    bank: "HDFC Bank",
    address: "14/8, Gurudwara Road, Karol Bagh, Central Delhi",
    city: "New Delhi",
    latitude: 28.6517,
    longitude: 77.1906,
    cctv_available: true,
    historical_fraud_count: 24,
  },
  {
    id: "LOC-DEL-03",
    name: "Laxmi Nagar Vikas Marg CSP Customer Service Hub",
    type: "CSP",
    bank: "Bank of Baroda CSP",
    address: "Main Vikas Marg, Near Metro Pillar 38, Laxmi Nagar",
    city: "East Delhi",
    latitude: 28.6304,
    longitude: 77.2773,
    cctv_available: false,
    historical_fraud_count: 31,
  },
  {
    id: "LOC-DEL-04",
    name: "Punjab National Bank — Chandni Chowk Town Hall ATM",
    type: "ATM",
    bank: "Punjab National Bank",
    address: "Opp. Town Hall, Chandni Chowk, Old Delhi",
    city: "Old Delhi",
    latitude: 28.6562,
    longitude: 77.2309,
    cctv_available: true,
    historical_fraud_count: 27,
  },
  {
    id: "LOC-DEL-05",
    name: "Noida Sector 18 Commercial Market Axis Bank ATM",
    type: "ATM",
    bank: "Axis Bank",
    address: "Atta Market, Sector 18, Noida",
    city: "Noida",
    latitude: 28.5708,
    longitude: 77.326,
    cctv_available: true,
    historical_fraud_count: 22,
  },
  {
    id: "LOC-DEL-06",
    name: "Noida Sector 62 Electronic City Banking Kiosk CSP",
    type: "CSP",
    bank: "Canara Bank CSP",
    address: "C-Block Commercial Complex, Sector 62, Noida",
    city: "Noida",
    latitude: 28.628,
    longitude: 77.3649,
    cctv_available: false,
    historical_fraud_count: 18,
  },
  {
    id: "LOC-DEL-07",
    name: "Gurugram Cyber City DLF Phase 2 ICICI ATM",
    type: "ATM",
    bank: "ICICI Bank",
    address: "Tower B, Cyber Hub, DLF Cyber City, Gurugram",
    city: "Gurugram",
    latitude: 28.4952,
    longitude: 77.0895,
    cctv_available: true,
    historical_fraud_count: 14,
  },
  {
    id: "LOC-DEL-08",
    name: "Gurugram Sector 14 Old Judicial Complex PNB ATM",
    type: "ATM",
    bank: "Punjab National Bank",
    address: "SCO 42, Sector 14 Market, Gurugram",
    city: "Gurugram",
    latitude: 28.4722,
    longitude: 77.0435,
    cctv_available: true,
    historical_fraud_count: 20,
  },
  {
    id: "LOC-DEL-09",
    name: "Faridabad NIT 1 Market State Bank of India ATM",
    type: "ATM",
    bank: "State Bank of India",
    address: "1-B Chowk, New Industrial Township, Faridabad",
    city: "Faridabad",
    latitude: 28.3954,
    longitude: 77.3082,
    cctv_available: true,
    historical_fraud_count: 16,
  },
  {
    id: "LOC-DEL-10",
    name: "Ghaziabad RDC Raj Nagar Commercial Hub ATM",
    type: "ATM",
    bank: "Bank of India",
    address: "Raj Nagar District Centre, RDC, Ghaziabad",
    city: "Ghaziabad",
    latitude: 28.6756,
    longitude: 77.4426,
    cctv_available: true,
    historical_fraud_count: 25,
  },
  {
    id: "LOC-DEL-11",
    name: "Rohini Sector 7 Deepali Chowk Indian Bank ATM",
    type: "ATM",
    bank: "Indian Bank",
    address: "Pocket 12, Sector 7, Rohini, North-West Delhi",
    city: "Delhi",
    latitude: 28.7056,
    longitude: 77.1194,
    cctv_available: true,
    historical_fraud_count: 17,
  },
  {
    id: "LOC-DEL-12",
    name: "Saket Community Centre HDFC ATM & CSP Point",
    type: "ATM",
    bank: "HDFC Bank",
    address: "PVR Anupam Complex, Saket, South Delhi",
    city: "New Delhi",
    latitude: 28.5245,
    longitude: 77.2066,
    cctv_available: true,
    historical_fraud_count: 15,
  },
  {
    id: "LOC-DEL-13",
    name: "Janakpuri District Centre SBI E-Corner",
    type: "ATM",
    bank: "State Bank of India",
    address: "District Centre, Janakpuri, West Delhi",
    city: "Delhi",
    latitude: 28.6289,
    longitude: 77.0788,
    cctv_available: true,
    historical_fraud_count: 21,
  },
  {
    id: "LOC-DEL-14",
    name: "Mayur Vihar Phase 1 Pocket 1 PNB CSP Kiosk",
    type: "CSP",
    bank: "PNB Banking Kiosk",
    address: "Acharya Niketan Market, Mayur Vihar Phase 1",
    city: "East Delhi",
    latitude: 28.6042,
    longitude: 77.2952,
    cctv_available: false,
    historical_fraud_count: 29,
  },
  {
    id: "LOC-DEL-15",
    name: "Dwarka Sector 12 City Centre Kotak Mahindra ATM",
    type: "ATM",
    bank: "Kotak Mahindra Bank",
    address: "Plot 3, Sector 12 Commercial Mall, Dwarka",
    city: "Delhi",
    latitude: 28.5921,
    longitude: 77.0398,
    cctv_available: true,
    historical_fraud_count: 13,
  },
  {
    id: "LOC-DEL-16",
    name: "South Extension Part 2 Ring Road Axis ATM",
    type: "ATM",
    bank: "Axis Bank",
    address: "E-Block, South Extension 2, New Delhi",
    city: "New Delhi",
    latitude: 28.5684,
    longitude: 77.2215,
    cctv_available: true,
    historical_fraud_count: 18,
  },
  {
    id: "LOC-DEL-17",
    name: "Pitampura Netaji Subhash Place BOB ATM",
    type: "ATM",
    bank: "Bank of Baroda",
    address: "Pearls Best Heights 1, NSP Complex, Pitampura",
    city: "Delhi",
    latitude: 28.6948,
    longitude: 77.1495,
    cctv_available: true,
    historical_fraud_count: 23,
  },
  {
    id: "LOC-DEL-18",
    name: "Kashmere Gate ISBT Concourse PNB ATM",
    type: "ATM",
    bank: "Punjab National Bank",
    address: "Inter-State Bus Terminal Arrival Hall, Kashmere Gate",
    city: "Old Delhi",
    latitude: 28.6675,
    longitude: 77.2312,
    cctv_available: true,
    historical_fraud_count: 34,
  },
  {
    id: "LOC-DEL-19",
    name: "Nizamuddin Railway Station Exit Gate SBI ATM",
    type: "ATM",
    bank: "State Bank of India",
    address: "Main Passenger Exit, Hazrat Nizamuddin Terminus",
    city: "New Delhi",
    latitude: 28.5888,
    longitude: 77.2536,
    cctv_available: true,
    historical_fraud_count: 36,
  },
  {
    id: "LOC-DEL-20",
    name: "Anand Vihar ISBT & Railway Station Cash Kiosk",
    type: "CSP",
    bank: "Gramin Bank CSP",
    address: "Chaudhary Charan Singh Kiosk Hub, Anand Vihar",
    city: "East Delhi",
    latitude: 28.6475,
    longitude: 77.3155,
    cctv_available: false,
    historical_fraud_count: 38,
  },
  {
    id: "LOC-DEL-21",
    name: "Nehru Place IT Market Paras Cinema ATM",
    type: "ATM",
    bank: "Canara Bank",
    address: "Nehru Place Commercial Enclave, South Delhi",
    city: "New Delhi",
    latitude: 28.5492,
    longitude: 77.2533,
    cctv_available: true,
    historical_fraud_count: 19,
  },
  {
    id: "LOC-DEL-22",
    name: "Sarita Vihar Pocket A Union Bank ATM",
    type: "ATM",
    bank: "Union Bank of India",
    address: "DDA Market, Pocket A, Sarita Vihar",
    city: "New Delhi",
    latitude: 28.5312,
    longitude: 77.2915,
    cctv_available: true,
    historical_fraud_count: 12,
  },
  {
    id: "LOC-DEL-23",
    name: "Badarpur Border Mathura Road CSP Outpost",
    type: "CSP",
    bank: "Fino Payments Bank CSP",
    address: "National Highway 2, Badarpur Border, Delhi",
    city: "Delhi-Faridabad Border",
    latitude: 28.4984,
    longitude: 77.3051,
    cctv_available: false,
    historical_fraud_count: 42,
  },
  {
    id: "LOC-DEL-24",
    name: "Shahdara Railway Station Road SBI ATM",
    type: "ATM",
    bank: "State Bank of India",
    address: "Circular Road, Near Metro Station, Shahdara",
    city: "East Delhi",
    latitude: 28.6738,
    longitude: 77.2882,
    cctv_available: true,
    historical_fraud_count: 28,
  },
  {
    id: "LOC-DEL-25",
    name: "Alipur GT Karnal Road Rural CSP Centre",
    type: "CSP",
    bank: "Airtel Payments Bank CSP",
    address: "Main GT Road, Alipur Block, North Delhi",
    city: "North Delhi",
    latitude: 28.7995,
    longitude: 77.1352,
    cctv_available: false,
    historical_fraud_count: 26,
  },
  {
    id: "LOC-DEL-26",
    name: "Najafgarh Main Dhansa Stand PNB ATM",
    type: "ATM",
    bank: "Punjab National Bank",
    address: "Dhansa Stand, Najafgarh, South-West Delhi",
    city: "Delhi",
    latitude: 28.6088,
    longitude: 76.9852,
    cctv_available: true,
    historical_fraud_count: 22,
  },
];

// ==========================================
// 3. INVESTIGATION CASES (12 DETAILED CASES)
// ==========================================
export const SEEDED_CASES: CaseDetail[] = [
  {
    id: "CASE-2026-4401",
    title: "Operation ShadowMule: Multi-State UPI Siphon to Delhi-NCR Cashout Ring",
    description: "Converged network of 6 electricity bill phishing victims. Stolen funds funneled through 3 mule layers within 14 minutes, targeting high-volume ATM/CSP extraction points across Laxmi Nagar and Old Delhi.",
    category: "Phishing / Mule Layering",
    total_amount_lost: 547000,
    created_at: "2026-09-28T09:14:00Z",
    status: "CRITICAL",
    primary_mule_account: "AXIS-918029381902",
    primary_mule_upi: "fastpay.sharma@okaxis",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4401"),
    risk_evaluation: {
      final_score: 92,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 88,
      general_reasons: [
        "Rapid burst of 6 inbound UPI transfers within 42 minutes exceeding standard daily velocity by 1,480%",
        "Immediate fan-out transfer to 3 secondary mule bank accounts within 180 seconds of deposit",
        "Geographic mismatch: Victim accounts in Mumbai/Pune/Delhi routing to device terminal in Jamtara/Nuh",
      ],
      behavior_score: 96,
      behavior_reasons: [
        "Beneficiary account dormant for 78 days prior to sudden ₹5.47 Lakh influx",
        "Device IMEI associated with 4 prior cybercrime incident reports on NCRP database",
        "Beneficiary UPI handle registered via burner SIM without linked biometric Aadhaar",
      ],
      human_readable_summary:
        "CRITICAL RISK (Score 92/100). The transaction topology displays textbook multi-hop mule layering designed to evade automated single-transaction bank threshold alarms. Urgent interception warranted.",
      evaluated_transactions_count: 14,
    },
  },
  {
    id: "CASE-2026-4402",
    title: "PowerGrid Phish: Telegram Part-Time Task Rating Extortion",
    description: "Victims lured with fake YouTube rating tasks, directed to invest in bogus crypto arbitrage pools via UPI QR codes. Funds funneled into student mule accounts.",
    category: "Investment / Task Fraud",
    total_amount_lost: 890000,
    created_at: "2026-09-28T08:15:00Z",
    status: "INVESTIGATING",
    primary_mule_account: "HDFC-4902198401",
    primary_mule_upi: "quickbill.support@ybl",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4402"),
    risk_evaluation: {
      final_score: 85,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 82,
      general_reasons: [
        "Split structuring: Multiple ₹49,990 transactions to avoid mandatory bank PAN validation thresholds",
        "Rapid withdrawal velocity across 4 different merchant VPAs",
      ],
      behavior_score: 88,
      behavior_reasons: [
        "Sudden 10x surge in account velocity compared to 90-day moving average",
        "High churn of unverified device sessions",
      ],
      human_readable_summary:
        "HIGH RISK (Score 85/100). Coordinated part-time job extortion ring using multiple layered student bank accounts.",
      evaluated_transactions_count: 11,
    },
  },
  {
    id: "CASE-2026-4403",
    title: "Operation IronShield: CBI Digital Arrest Impersonation Syndicate",
    description: "Elderly victims coerced into liquidating fixed deposits following fraudulent video calls impersonating law enforcement officers.",
    category: "Digital Arrest Impersonation",
    total_amount_lost: 1970000,
    created_at: "2026-09-28T07:30:00Z",
    status: "CRITICAL",
    primary_mule_account: "ICICI-0019283918",
    primary_mule_upi: "investigate.cbi@centralgov",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4403"),
    risk_evaluation: {
      final_score: 98,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 95,
      general_reasons: [
        "Lump sum liquidation transfers exceeding ₹6 Lakh directly to unverified individual VPA",
        "Immediate cash withdrawal tokens generated across multiple Delhi NCR bank branches",
      ],
      behavior_score: 100,
      behavior_reasons: [
        "Unprecedented transfer size from senior citizen demographic with zero prior high-value transfers",
        "Remote desktop software (AnyDesk/TeamViewer) active during transaction authorization",
      ],
      human_readable_summary:
        "CRITICAL RISK (Score 98/100). High-value digital arrest coercion syndicate. Funds in terminal distribution phase.",
      evaluated_transactions_count: 8,
    },
  },
  {
    id: "CASE-2026-4404",
    title: "Predatory Instant Loan APK Contact-Scraping Extortion",
    description: "Malicious mobile apps requesting intrusive contact/photo permissions, deploying morph-photo blackmail for extortion payments.",
    category: "App Extortion",
    total_amount_lost: 293000,
    created_at: "2026-09-28T06:10:00Z",
    status: "INVESTIGATING",
    primary_mule_account: "KOTAK-9102839102",
    primary_mule_upi: "settleloan.recovery@kotak",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4404"),
    risk_evaluation: {
      final_score: 79,
      decision: "VERIFY",
      history_status: "LIMITED_HISTORY",
      general_score: 76,
      general_reasons: ["Aggressive recurring collections from distinct UPI IDs in high-frequency succession"],
      behavior_score: 82,
      behavior_reasons: ["Frequent change in registered handset device tokens"],
      human_readable_summary:
        "MODERATE TO HIGH RISK (Score 79/100). Predator loan recovery network operating shell VPAs.",
      evaluated_transactions_count: 19,
    },
  },
  {
    id: "CASE-2026-4405",
    title: "Vanguard Wealth: WhatsApp Fake Institutional IPO Syndicate",
    description: "Victims directed into dummy institutional trading accounts with falsified balance sheets, demanding upfront release fees via UPI.",
    category: "Securities Fraud",
    total_amount_lost: 3530000,
    created_at: "2026-09-27T16:00:00Z",
    status: "CRITICAL",
    primary_mule_account: "SBI-3019283019",
    primary_mule_upi: "vanguard.institutional@sbi",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4405"),
    risk_evaluation: {
      final_score: 96,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 94,
      general_reasons: ["Multi-crore throughput funneling into newly incorporated private limited accounts"],
      behavior_score: 98,
      behavior_reasons: ["Instant overseas remittance conversions and high-value cash exits"],
      human_readable_summary: "CRITICAL RISK (Score 96/100). Major institutional securities scam operating nationwide.",
      evaluated_transactions_count: 23,
    },
  },
  {
    id: "CASE-2026-4406",
    title: "Telecom SimSwap & Banking OTP Interception Ring",
    description: "Sim card duplicate swap attacks intercepting 2FA authorizations across major public sector banks.",
    category: "Identity Theft",
    total_amount_lost: 235000,
    created_at: "2026-09-27T14:30:00Z",
    status: "RESOLVED",
    primary_mule_account: "PNB-1029381920",
    primary_mule_upi: "telecom.support49@pnb",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4406"),
    risk_evaluation: {
      final_score: 88,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 85,
      general_reasons: ["Device mismatch post SIM-reissue event within 2 hours"],
      behavior_score: 90,
      behavior_reasons: ["Immediate password resets accompanied by transfer velocity spike"],
      human_readable_summary: "HIGH RISK (Score 88/100). Sim-swap identity takeover successfully resolved.",
      evaluated_transactions_count: 6,
    },
  },
  {
    id: "CASE-2026-4407",
    title: "Marketplace QR Code Reverse-Payment Scam",
    description: "Scammers posing as army personnel or buyers, sending 'Receive Money' QR codes that initiate debit instead of credit.",
    category: "QR Code Phishing",
    total_amount_lost: 168000,
    created_at: "2026-09-27T11:00:00Z",
    status: "DISPATCHED",
    primary_mule_account: "BOB-2019283019",
    primary_mule_upi: "armypost.canteen@okaxis",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4407"),
    risk_evaluation: {
      final_score: 74,
      decision: "VERIFY",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 72,
      general_reasons: ["Inverse transaction request patterns across OLX/Facebook Marketplace listings"],
      behavior_score: 76,
      behavior_reasons: ["High count of incoming payment link rejections followed by sudden approvals"],
      human_readable_summary: "MODERATE RISK (Score 74/100). Marketplace QR code fraud.",
      evaluated_transactions_count: 9,
    },
  },
  {
    id: "CASE-2026-4408",
    title: "Matrimonial Profile Honeytrap & NRI Gift Customs Extortion",
    description: "Impersonators claiming to be NRI doctors sending luxury parcels held by fake customs officers demanding clearance duties.",
    category: "Impersonation",
    total_amount_lost: 395000,
    created_at: "2026-09-26T18:00:00Z",
    status: "INVESTIGATING",
    primary_mule_account: "UNION-9019283019",
    primary_mule_upi: "customs.clearance.delhi@uboi",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4408"),
    risk_evaluation: {
      final_score: 86,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 84,
      general_reasons: ["Unregistered personal accounts claiming government customs tax clearance"],
      behavior_score: 88,
      behavior_reasons: ["Sequential escalations in payment demands from single victim"],
      human_readable_summary: "HIGH RISK (Score 86/100). Matrimonial parcel extortion ring.",
      evaluated_transactions_count: 7,
    },
  },
  {
    id: "CASE-2026-4409",
    title: "FedEx Narcotics Parcel Courier Impersonation Ring",
    description: "Automated IVR calls claiming illegal narcotics seized in courier parcel under victim's Aadhaar, demanding fund verification.",
    category: "Courier Narcotics Scam",
    total_amount_lost: 770000,
    created_at: "2026-09-26T14:00:00Z",
    status: "CRITICAL",
    primary_mule_account: "YES-0918203910",
    primary_mule_upi: "narcotics.verification@ybl",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4409"),
    risk_evaluation: {
      final_score: 94,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 92,
      general_reasons: ["Rapid debit transfers immediately followed by ATM withdrawals in border regions"],
      behavior_score: 96,
      behavior_reasons: ["Burner SIM registrations and VPN-masked IP connections"],
      human_readable_summary: "CRITICAL RISK (Score 94/100). Narcotics courier impersonation syndicate.",
      evaluated_transactions_count: 12,
    },
  },
  {
    id: "CASE-2026-4410",
    title: "Credit Card Reward Point Expiry SMS Phishing",
    description: "Phishing links disguised as bank reward points portals harvesting OTPs and executing unauthorized e-wallet top-ups.",
    category: "SMS Phishing",
    total_amount_lost: 205000,
    created_at: "2026-09-26T10:00:00Z",
    status: "ACKNOWLEDGED",
    primary_mule_account: "IDFC-8192039102",
    primary_mule_upi: "rewards.redemption@idfc",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4410"),
    risk_evaluation: {
      final_score: 81,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 80,
      general_reasons: ["High-speed micro-charges across gift voucher aggregators"],
      behavior_score: 83,
      behavior_reasons: ["Automated bot execution of card verification routines"],
      human_readable_summary: "HIGH RISK (Score 81/100). Automated reward phishing campaign.",
      evaluated_transactions_count: 15,
    },
  },
  {
    id: "CASE-2026-4411",
    title: "Hotel Booking Google Review Work-From-Home Syndicate",
    description: "Victims recruited to write fake Google reviews, later coerced into crypto transfer schemes.",
    category: "Employment Scam",
    total_amount_lost: 365000,
    created_at: "2026-09-25T16:00:00Z",
    status: "DISPATCHED",
    primary_mule_account: "CANARA-9102938190",
    primary_mule_upi: "travelmedia.ratings@cnrb",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4411"),
    risk_evaluation: {
      final_score: 83,
      decision: "BLOCK",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 81,
      general_reasons: ["Fast payment distribution to multiple Level-2 runner accounts"],
      behavior_score: 85,
      behavior_reasons: ["Dormant student accounts active only during night hours"],
      human_readable_summary: "HIGH RISK (Score 83/100). Review manipulation task network.",
      evaluated_transactions_count: 10,
    },
  },
  {
    id: "CASE-2026-4412",
    title: "Fake KBC WhatsApp Lucky Draw Lottery Scheme",
    description: "WhatsApp audio notes promising lottery prizes subject to GST and processing fees paid in advance.",
    category: "Lottery Scam",
    total_amount_lost: 300000,
    created_at: "2026-09-25T12:00:00Z",
    status: "RESOLVED",
    primary_mule_account: "SBI-0918293810",
    primary_mule_upi: "kbc.lottery.tax@sbi",
    complaints: SEEDED_COMPLAINTS.filter((c) => c.case_id === "CASE-2026-4412"),
    risk_evaluation: {
      final_score: 77,
      decision: "VERIFY",
      history_status: "SUFFICIENT_HISTORY",
      general_score: 75,
      general_reasons: ["Victim payments received across rural CSP branches"],
      behavior_score: 79,
      behavior_reasons: ["Repeated cash withdrawals from rural kiosks without CCTV coverage"],
      human_readable_summary: "MODERATE RISK (Score 77/100). WhatsApp lottery scam successfully contained.",
      evaluated_transactions_count: 8,
    },
  },
];

// ==========================================
// 4. MULTI-HOP NETWORK GRAPH (PER CASE)
// ==========================================
export function getSeededNetworkGraph(caseId: string): EntityNetworkGraph {
  if (caseId === "CASE-2026-4401") {
    return {
      central_mule_node: "MULE-L1-01",
      total_layers: 4,
      summary: "6 Victims → Primary Mule (fastpay.sharma@okaxis) → 3 L2 Mules → 2 Withdrawal Runner Nodes.",
      nodes: [
        { id: "VIC-01", label: "PRAISY I (Victim)", type: "victim", details: { bank: "HDFC", amount: 45000 } },
        { id: "VIC-02", label: "ARYAN MANOJ (Victim)", type: "victim", details: { bank: "ICICI", amount: 82000 } },
        { id: "VIC-03", label: "ABHINAV (Victim)", type: "victim", details: { bank: "SBI", amount: 120000 } },
        { id: "VIC-04", label: "ANIRUDH (Victim)", type: "victim", details: { bank: "Axis", amount: 60000 } },
        { id: "VIC-05", label: "ARYAANSH (Victim)", type: "victim", details: { bank: "Kotak", amount: 95000 } },
        { id: "VIC-06", label: "Vikas Aggarwal (Victim)", type: "victim", details: { bank: "PNB", amount: 145000 } },
        { id: "MULE-L1-01", label: "fastpay.sharma@okaxis (L1 Mule)", type: "mule_l1", details: { bank: "Axis Bank", balance: 547000 } },
        { id: "MULE-L2-01", label: "rk.trading.agency@sbi (L2 Mule)", type: "mule_l2", details: { bank: "SBI", amount: 180000 } },
        { id: "MULE-L2-02", label: "suraj.ent@icici (L2 Mule)", type: "mule_l2", details: { bank: "ICICI", amount: 200000 } },
        { id: "MULE-L2-03", label: "quickpay.delhi@pnb (L2 Mule)", type: "mule_l2", details: { bank: "PNB", amount: 167000 } },
        { id: "RUNNER-01", label: "Runner Cash-Out Token #1", type: "runner_token", details: { channel: "Cardless ATM OTP" } },
        { id: "RUNNER-02", label: "CSP Biometric Terminal Token #2", type: "runner_token", details: { channel: "AePS Biometric CSP" } },
        { id: "ATM-TARGET-01", label: "Connaught Place SBI ATM", type: "atm_csp", details: { id: "LOC-DEL-01" } },
        { id: "CSP-TARGET-02", label: "Laxmi Nagar BoB CSP Hub", type: "atm_csp", details: { id: "LOC-DEL-03" } },
      ],
      edges: [
        { source: "VIC-01", target: "MULE-L1-01", label: "₹45,000", amount: 45000, timestamp: "09:14:02", edge_type: "upi" },
        { source: "VIC-02", target: "MULE-L1-01", label: "₹82,000", amount: 82000, timestamp: "09:30:15", edge_type: "upi" },
        { source: "VIC-03", target: "MULE-L1-01", label: "₹1,20,000", amount: 120000, timestamp: "09:45:22", edge_type: "upi" },
        { source: "VIC-04", target: "MULE-L1-01", label: "₹60,000", amount: 60000, timestamp: "10:10:04", edge_type: "upi" },
        { source: "VIC-05", target: "MULE-L1-01", label: "₹95,000", amount: 95000, timestamp: "10:22:45", edge_type: "upi" },
        { source: "VIC-06", target: "MULE-L1-01", label: "₹1,45,000", amount: 145000, timestamp: "10:40:19", edge_type: "upi" },
        { source: "MULE-L1-01", target: "MULE-L2-01", label: "₹1,80,000 (Layer 2)", amount: 180000, timestamp: "10:42:01", edge_type: "layering" },
        { source: "MULE-L1-01", target: "MULE-L2-02", label: "₹2,00,000 (Layer 2)", amount: 200000, timestamp: "10:43:10", edge_type: "layering" },
        { source: "MULE-L1-01", target: "MULE-L2-03", label: "₹1,67,000 (Layer 2)", amount: 167000, timestamp: "10:44:28", edge_type: "layering" },
        { source: "MULE-L2-01", target: "RUNNER-01", label: "Cardless PIN", amount: 180000, timestamp: "10:46:12", edge_type: "token" },
        { source: "MULE-L2-02", target: "RUNNER-01", label: "ATM Direct Card", amount: 200000, timestamp: "10:47:05", edge_type: "token" },
        { source: "MULE-L2-03", target: "RUNNER-02", label: "AePS Biometric", amount: 167000, timestamp: "10:48:33", edge_type: "token" },
        { source: "RUNNER-01", target: "ATM-TARGET-01", label: "Imminent Exit", amount: 380000, timestamp: "11:00:00", edge_type: "withdrawal" },
        { source: "RUNNER-02", target: "CSP-TARGET-02", label: "Imminent Exit", amount: 167000, timestamp: "11:05:00", edge_type: "withdrawal" },
      ],
    };
  }

  // Generic fallback topology for any other case
  const c = SEEDED_CASES.find((x) => x.id === caseId) || SEEDED_CASES[0];
  return {
    central_mule_node: "MULE-L1",
    total_layers: 3,
    summary: `${c.complaints.length} Victims → Primary Mule (${c.primary_mule_upi}) → Layered Cash-Out Endpoints.`,
    nodes: [
      ...c.complaints.slice(0, 4).map((comp, idx) => ({
        id: `VIC-${idx + 1}`,
        label: `${comp.victim_name} (Victim)`,
        type: "victim",
        details: { bank: comp.victim_bank, amount: comp.reported_amount },
      })),
      { id: "MULE-L1", label: `${c.primary_mule_upi || "Primary Mule"}`, type: "mule_l1", details: { account: c.primary_mule_account } },
      { id: "MULE-L2-A", label: "Secondary Mule A", type: "mule_l2", details: { bank: "State Bank" } },
      { id: "MULE-L2-B", label: "Secondary Mule B", type: "mule_l2", details: { bank: "Private Bank" } },
      { id: "RUNNER-A", label: "Physical Runner Token", type: "runner_token", details: { mode: "ATM Cashout" } },
    ],
    edges: [
      ...c.complaints.slice(0, 4).map((comp, idx) => ({
        source: `VIC-${idx + 1}`,
        target: "MULE-L1",
        label: `₹${comp.reported_amount.toLocaleString("en-IN")}`,
        amount: comp.reported_amount,
        timestamp: "09:30:00",
        edge_type: "upi",
      })),
      { source: "MULE-L1", target: "MULE-L2-A", label: "50% Fan-out", edge_type: "layering" },
      { source: "MULE-L1", target: "MULE-L2-B", label: "50% Fan-out", edge_type: "layering" },
      { source: "MULE-L2-A", target: "RUNNER-A", label: "Extraction", edge_type: "withdrawal" },
      { source: "MULE-L2-B", target: "RUNNER-A", label: "Extraction", edge_type: "withdrawal" },
    ],
  };
}

// ==========================================
// 5. DETERMINISTIC CASHOUT PREDICTION ENGINE
// ==========================================
export function predictSeededCashout(caseId: string): CashoutPredictionResponse {
  const c = SEEDED_CASES.find((x) => x.id === caseId) || SEEDED_CASES[0];
  const targetAmount = c.total_amount_lost;

  const locations = [
    {
      loc: SEEDED_HOTSPOTS[2], // Laxmi Nagar BoB CSP Hub
      prob: 0.94,
      risk: "CRITICAL" as const,
      dist: 1.4,
      window: "12 - 25 mins",
      reasons: [
        "Unusually high historical fraud exit volume (31 confirmed incidents in past 60 days)",
        "Absence of active CCTV recording capability creates tactical blindspot for runner",
        "Geographic proximity (1.4 km) from last identified mobile tower triangulation coordinate",
        "CSP daily cash liquidity limit matches remaining layered balance profile",
      ],
    },
    {
      loc: SEEDED_HOTSPOTS[0], // Connaught Place SBI ATM
      prob: 0.88,
      risk: "CRITICAL" as const,
      dist: 2.8,
      window: "20 - 35 mins",
      reasons: [
        "High-capacity multi-cassette ATM with maximum daily withdrawal allowance",
        "Direct metro transit corridor connecting from L2 mule account holder's registered address",
        "19 prior suspicious cardless withdrawal patterns recorded in NCRP registry",
      ],
    },
    {
      loc: SEEDED_HOTSPOTS[1], // Karol Bagh HDFC ATM
      prob: 0.81,
      risk: "HIGH" as const,
      dist: 3.6,
      window: "30 - 45 mins",
      reasons: [
        "Multiple merchant VPAs registered under same syndicate operating within 500m radius",
        "24 historical cybercrime exit reports flagged by Central Delhi Police Cyber Cell",
      ],
    },
    {
      loc: SEEDED_HOTSPOTS[3], // Chandni Chowk PNB ATM
      prob: 0.74,
      risk: "HIGH" as const,
      dist: 4.1,
      window: "40 - 60 mins",
      reasons: [
        "Dense commercial wholesale foot traffic facilitates undetected physical runner extraction",
        "Prior coordination nexus observed between Chandni Chowk and Jamtara cyber cells",
      ],
    },
    {
      loc: SEEDED_HOTSPOTS[4], // Noida Sector 18 Axis ATM
      prob: 0.65,
      risk: "MODERATE" as const,
      dist: 6.8,
      window: "50 - 75 mins",
      reasons: [
        "High evening footfall and cross-border transit point between Delhi and Gautam Buddha Nagar",
      ],
    },
  ];

  return {
    case_id: c.id,
    target_amount: targetAmount,
    predicted_locations: locations.map((item, idx) => ({
      rank: idx + 1,
      location_id: item.loc.id,
      name: item.loc.name,
      type: item.loc.type,
      bank: item.loc.bank,
      latitude: item.loc.latitude,
      longitude: item.loc.longitude,
      probability_score: item.prob,
      risk_level: item.risk,
      distance_km: item.dist,
      estimated_time_window: item.window,
      reason_factors: item.reasons,
    })),
    model_version: "XGBoost-SpatialTree-v2.6.4",
    methodology_note:
      "Rankings computed via gradient-boosted decision ensemble analyzing transaction velocity vectors, device tower proximity, historical cash-out incident density, and ATM cash availability.",
    recommended_actions: [
      "Transmit urgent alert to Delhi Police Cyber Cell Beat Patrol near Laxmi Nagar Vikas Marg",
      "Issue urgent debit-freeze notice to Bank of Baroda Fraud Monitoring Operations for CSP Terminal",
      "Coordinate with State Bank of India Nodal Desk for immediate ATM cardless withdrawal block",
    ],
  };
}

// ==========================================
// 6. SEEDED TACTICAL ALERTS (~32 RECORDS)
// ==========================================
export const SEEDED_ALERTS: AlertResponse[] = [
  {
    id: "ALT-2026-901",
    case_id: "CASE-2026-4401",
    case_title: "Operation ShadowMule: Multi-State UPI Siphon",
    priority: "CRITICAL",
    target_agencies: ["Delhi Police Cyber Crime Unit", "State Bank of India Fraud Nodal Desk", "I4C Registry"],
    predicted_locations: [
      { name: "Laxmi Nagar Vikas Marg BoB CSP Hub", id: "LOC-DEL-03", probability: 0.94 },
      { name: "SBI Connaught Place Inner Circle ATM", id: "LOC-DEL-01", probability: 0.88 },
    ],
    dispatched_at: "2026-09-28T10:48:00Z",
    status: "DISPATCHED",
    action_code: "ACT-FREEZE-INTERCEPT",
    summary:
      "CRITICAL: Imminent ₹5.47 Lakh cash-out flagged across Laxmi Nagar Vikas Marg and Connaught Place. 6 converged complaints. Suspect velocity 180s.",
  },
  {
    id: "ALT-2026-902",
    case_id: "CASE-2026-4403",
    case_title: "Operation IronShield: CBI Digital Arrest Impersonation",
    priority: "CRITICAL",
    target_agencies: ["CBI Cyber Division", "ICICI Bank Fraud Operations", "Delhi Police Special Cell"],
    predicted_locations: [
      { name: "HDFC Karol Bagh Gurudwara Road ATM", id: "LOC-DEL-02", probability: 0.92 },
      { name: "Chandni Chowk Town Hall PNB ATM", id: "LOC-DEL-04", probability: 0.85 },
    ],
    dispatched_at: "2026-09-28T09:55:00Z",
    status: "ACKNOWLEDGED",
    action_code: "ACT-EMERGENCY-FREEZE",
    summary:
      "CRITICAL: Senior citizen digital arrest extortion (₹19.7 Lakh). Multi-hop liquidation in progress. ICICI nodal officer acknowledged account restriction.",
  },
  {
    id: "ALT-2026-903",
    case_id: "CASE-2026-4402",
    case_title: "PowerGrid Phish: Telegram Part-Time Task Rating",
    priority: "HIGH",
    target_agencies: ["Noida Police Cyber Cell", "HDFC Bank Fraud Desk"],
    predicted_locations: [
      { name: "Noida Sector 18 Commercial Market Axis ATM", id: "LOC-DEL-05", probability: 0.84 },
      { name: "Noida Sector 62 Electronic City CSP", id: "LOC-DEL-06", probability: 0.78 },
    ],
    dispatched_at: "2026-09-28T09:40:00Z",
    status: "DISPATCHED",
    action_code: "ACT-PATROL-DISPATCH",
    summary:
      "HIGH: 4 complaints converged against quickbill.support@ybl. Runner dispatched to Sector 18 Noida ATM cluster.",
  },
  {
    id: "ALT-2026-904",
    case_id: "CASE-2026-4405",
    case_title: "Vanguard Wealth: WhatsApp Fake IPO Syndicate",
    priority: "CRITICAL",
    target_agencies: ["Gurugram Cyber Crime Cell", "SEBI Surveillance Desk", "State Bank of India Nodal"],
    predicted_locations: [
      { name: "Gurugram Cyber City DLF Phase 2 ICICI ATM", id: "LOC-DEL-07", probability: 0.91 },
      { name: "Gurugram Sector 14 PNB ATM", id: "LOC-DEL-08", probability: 0.83 },
    ],
    dispatched_at: "2026-09-28T08:50:00Z",
    status: "RESOLVED",
    action_code: "ACT-CONTAINMENT-CONFIRMED",
    summary:
      "CRITICAL / RESOLVED: ₹35.3 Lakh corporate account syndicate intercepted. 14 mule VPAs placed under debit-freeze before cash exit.",
  },
  {
    id: "ALT-2026-905",
    case_id: "CASE-2026-4404",
    case_title: "Predatory Instant Loan APK Contact-Scraping Extortion",
    priority: "MODERATE",
    target_agencies: ["Faridabad Police Cyber Cell", "Kotak Mahindra Fraud Monitoring"],
    predicted_locations: [
      { name: "Faridabad NIT 1 Market State Bank ATM", id: "LOC-DEL-09", probability: 0.72 },
    ],
    dispatched_at: "2026-09-28T07:50:00Z",
    status: "GENERATED",
    action_code: "ACT-WATCHLIST-ALERT",
    summary:
      "MODERATE: Recurring recovery micro-transactions flagged on settleloan.recovery@kotak. Target ATM under observation.",
  },
  {
    id: "ALT-2026-906",
    case_id: "CASE-2026-4407",
    case_title: "Marketplace QR Code Reverse-Payment Scam",
    priority: "MODERATE",
    target_agencies: ["East Delhi Police Cyber Cell", "Axis Bank Nodal"],
    predicted_locations: [
      { name: "Mayur Vihar Phase 1 PNB CSP Kiosk", id: "LOC-DEL-14", probability: 0.74 },
    ],
    dispatched_at: "2026-09-27T12:15:00Z",
    status: "ACKNOWLEDGED",
    action_code: "ACT-MERCHANT-SUSPEND",
    summary:
      "MODERATE: Marketplace reverse QR debit ring. East Delhi Cyber Cell confirmed merchant terminal blacklisting.",
  },
  {
    id: "ALT-2026-907",
    case_id: "CASE-2026-4408",
    case_title: "Matrimonial Profile Honeytrap & NRI Customs Extortion",
    priority: "HIGH",
    target_agencies: ["Noida Police Cyber Cell", "Union Bank Fraud Cell"],
    predicted_locations: [
      { name: "Noida Sector 62 Electronic City CSP", id: "LOC-DEL-06", probability: 0.82 },
    ],
    dispatched_at: "2026-09-27T19:30:00Z",
    status: "DISPATCHED",
    action_code: "ACT-PATROL-DISPATCH",
    summary:
      "HIGH: False customs clearance payment demands routed via fake Union Bank account. Beat officer notified.",
  },
  {
    id: "ALT-2026-908",
    case_id: "CASE-2026-4409",
    case_title: "FedEx Narcotics Parcel Courier Impersonation Ring",
    priority: "CRITICAL",
    target_agencies: ["Delhi Police Special Cell", "NCB Cyber Desk", "Yes Bank Fraud Monitoring"],
    predicted_locations: [
      { name: "Badarpur Border Mathura Road CSP Outpost", id: "LOC-DEL-23", probability: 0.93 },
    ],
    dispatched_at: "2026-09-27T15:20:00Z",
    status: "DISPATCHED",
    action_code: "ACT-EMERGENCY-INTERCEPT",
    summary:
      "CRITICAL: Narcotics IVR impersonation syndicate cash-out runner active near Delhi-Faridabad border outpost.",
  },
  {
    id: "ALT-2026-909",
    case_id: "CASE-2026-4410",
    case_title: "Credit Card Reward Point Expiry SMS Phishing",
    priority: "HIGH",
    target_agencies: ["IDFC First Bank Fraud Team", "Delhi Police Cyber Cell"],
    predicted_locations: [
      { name: "Nehru Place IT Market Paras Cinema ATM", id: "LOC-DEL-21", probability: 0.85 },
    ],
    dispatched_at: "2026-09-26T11:00:00Z",
    status: "ACKNOWLEDGED",
    action_code: "ACT-FREEZE-NOTICE",
    summary:
      "HIGH: Automated OTP harvesting campaign. IDFC nodal officer flagged 12 linked cards for forced reissue.",
  },
  {
    id: "ALT-2026-910",
    case_id: "CASE-2026-4411",
    case_title: "Hotel Booking Google Review Work-From-Home Syndicate",
    priority: "HIGH",
    target_agencies: ["Faridabad Cyber Crime Police", "Canara Bank Nodal"],
    predicted_locations: [
      { name: "Faridabad NIT 1 Market SBI ATM", id: "LOC-DEL-09", probability: 0.81 },
    ],
    dispatched_at: "2026-09-25T17:30:00Z",
    status: "DISPATCHED",
    action_code: "ACT-RUNNER-INTERCEPTION",
    summary:
      "HIGH: Rating task extortion ring runner located near NIT Faridabad market. Alert sent to local patrol unit.",
  },
  {
    id: "ALT-2026-911",
    case_id: "CASE-2026-4412",
    case_title: "Fake KBC WhatsApp Lucky Draw Lottery Scheme",
    priority: "MODERATE",
    target_agencies: ["Ghaziabad Police Cyber Cell", "State Bank of India"],
    predicted_locations: [
      { name: "Ghaziabad RDC Raj Nagar Commercial Hub ATM", id: "LOC-DEL-10", probability: 0.77 },
    ],
    dispatched_at: "2026-09-25T13:45:00Z",
    status: "RESOLVED",
    action_code: "ACT-CONTAINMENT-CONFIRMED",
    summary:
      "MODERATE / RESOLVED: WhatsApp lottery syndicate runner apprehended at Raj Nagar ATM with counterfeit debit cards.",
  },
  {
    id: "ALT-2026-912",
    case_id: "CASE-2026-4406",
    case_title: "Telecom SimSwap & Banking OTP Interception Ring",
    priority: "HIGH",
    target_agencies: ["DoT Cyber Intelligence", "PNB Fraud Monitoring"],
    predicted_locations: [
      { name: "Kashmere Gate ISBT Concourse PNB ATM", id: "LOC-DEL-18", probability: 0.86 },
    ],
    dispatched_at: "2026-09-27T15:00:00Z",
    status: "RESOLVED",
    action_code: "ACT-SIM-REVOKED",
    summary:
      "HIGH / RESOLVED: Impersonated duplicate SIM barred. Associated PNB account secured within 20 minutes.",
  },
];

// ==========================================
// 7. COMPREHENSIVE DASHBOARD STATS
// ==========================================
export function getSeededDashboardStats(): DashboardStats {
  const totalAmount = SEEDED_CASES.reduce((sum, c) => sum + c.total_amount_lost, 0);
  const criticalCases = SEEDED_CASES.filter((c) => c.status === "CRITICAL").length;

  return {
    total_complaints: SEEDED_COMPLAINTS.length,
    total_cases: SEEDED_CASES.length,
    amount_at_risk: totalAmount,
    high_risk_cases_count: criticalCases,
    active_hotspots_count: SEEDED_HOTSPOTS.length,
    recent_complaints: SEEDED_COMPLAINTS.slice(0, 10),
    recent_alerts: SEEDED_ALERTS.slice(0, 8),
    hotspot_locations: SEEDED_HOTSPOTS,
  };
}

// ==========================================
// 8. GROUPED SEARCH INDEX
// ==========================================
export interface SearchGroupResult {
  cases: CaseDetail[];
  accounts: { case_id: string; title: string; upi: string; account: string }[];
  complaints: Complaint[];
}

export function searchSeededIntelligence(query: string): SearchGroupResult {
  const q = query.trim().toLowerCase();
  if (!q) {
    return {
      cases: SEEDED_CASES.slice(0, 4),
      accounts: SEEDED_CASES.slice(0, 3).map((c) => ({
        case_id: c.id,
        title: c.title,
        upi: c.primary_mule_upi || "—",
        account: c.primary_mule_account || "—",
      })),
      complaints: SEEDED_COMPLAINTS.slice(0, 3),
    };
  }

  const cases = SEEDED_CASES.filter(
    (c) =>
      c.id.toLowerCase().includes(q) ||
      c.title.toLowerCase().includes(q) ||
      c.category.toLowerCase().includes(q)
  ).slice(0, 5);

  const accounts = SEEDED_CASES.filter(
    (c) =>
      (c.primary_mule_upi && c.primary_mule_upi.toLowerCase().includes(q)) ||
      (c.primary_mule_account && c.primary_mule_account.toLowerCase().includes(q))
  )
    .map((c) => ({
      case_id: c.id,
      title: c.title,
      upi: c.primary_mule_upi || "—",
      account: c.primary_mule_account || "—",
    }))
    .slice(0, 5);

  const complaints = SEEDED_COMPLAINTS.filter(
    (comp) =>
      comp.id.toLowerCase().includes(q) ||
      comp.victim_name.toLowerCase().includes(q) ||
      comp.victim_upi.toLowerCase().includes(q) ||
      comp.fraud_category.toLowerCase().includes(q)
  ).slice(0, 5);

  return { cases, accounts, complaints };
}
